<?php include_once('wudata.php');?>
<?php echo $wuskydayTime?>,<?php echo $wuskydayWinddir; ?>,<?php echo $wuskydayWinddircardinal; ?>,
<?php echo $wuskydayTime1?>,<?php echo $wuskydayWinddir1; ?>,<?php echo $wuskydayWinddircardinal1; ?>,
<?php echo $wuskydayTime2?>,<?php echo $wuskydayWinddir2; ?>,<?php echo $wuskydayWinddircardinal2; ?>,
<?php echo $wuskydayTime3?>,<?php echo $wuskydayWinddir3; ?>,<?php echo $wuskydayWinddircardinal3; ?>,
<?php echo $wuskydayTime4?>,<?php echo $wuskydayWinddir4; ?>,<?php echo $wuskydayWinddircardinal4; ?>,
<?php echo $wuskydayTime5?>,<?php echo $wuskydayWinddir5; ?>,<?php echo $wuskydayWinddircardinal5; ?>,
<?php echo $wuskydayTime6?>,<?php echo $wuskydayWinddir6; ?>,<?php echo $wuskydayWinddircardinal6; ?>,
<?php echo $wuskydayTime7?>,<?php echo $wuskydayWinddir7; ?>,<?php echo $wuskydayWinddircardinal7; ?>,
<?php echo $wuskydayTime8?>,<?php echo $wuskydayWinddir8; ?>,<?php echo $wuskydayWinddircardinal8; ?>,